spring.datasource.url=jdbc:postgresql://localhost:5432/springPoc
spring.datasource.username=tu_usuario
spring.datasource.password=db_password
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
server.port=8081