spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/springPoc}
spring.datasource.username=${DB_USERNAME:tu_usuario}
spring.datasource.password=${DB_PASSWORD:db_password}
spring.datasource.driver-class-name=${DB_DRIVER:org.postgresql.Driver}
spring.jpa.database-platform=${DB_DIALECT:org.hibernate.dialect.PostgreSQLDialect}
spring.jpa.hibernate.ddl-auto=${DB_DDL_AUTO:update}
server.port=${PORT:8081}