server.port=${PORT:8082}

azure.servicebus.connection-string=${AZURE_SERVICEBUS_CONNECTION_STRING:}
azure.servicebus.queue-name=${SB_QUEUE_NAME:}
azure.servicebus.topic-name=${SB_TOPIC_NAME:}
azure.servicebus.subscription-name=${SB_SUBSCRIPTION_NAME:}
